// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOKTX0wEzzqvxrgB_Qkh35xOO5iIDiLI',
    appId: '1:501071252647:web:646e907a1b18ae821b1f82',
    messagingSenderId: '501071252647',
    projectId: 'garage-app-ci',
    authDomain: 'garage-app-ci.firebaseapp.com',
    storageBucket: 'garage-app-ci.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuc-oXqet13dIREXqc7yBUFfVdv5uJyOs',
    appId: '1:501071252647:android:de4379c25318bf2d1b1f82',
    messagingSenderId: '501071252647',
    projectId: 'garage-app-ci',
    storageBucket: 'garage-app-ci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsb6WpkmY8_RUolqpcwZC-E8HMDgSD7w',
    appId: '1:501071252647:ios:0551afa0be769bc81b1f82',
    messagingSenderId: '501071252647',
    projectId: 'garage-app-ci',
    storageBucket: 'garage-app-ci.firebasestorage.app',
    iosBundleId: 'com.example.garageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQsb6WpkmY8_RUolqpcwZC-E8HMDgSD7w',
    appId: '1:501071252647:ios:0551afa0be769bc81b1f82',
    messagingSenderId: '501071252647',
    projectId: 'garage-app-ci',
    storageBucket: 'garage-app-ci.firebasestorage.app',
    iosBundleId: 'com.example.garageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuOKTX0wEzzqvxrgB_Qkh35xOO5iIDiLI',
    appId: '1:501071252647:web:56c1a75d9e2f892e1b1f82',
    messagingSenderId: '501071252647',
    projectId: 'garage-app-ci',
    authDomain: 'garage-app-ci.firebaseapp.com',
    storageBucket: 'garage-app-ci.firebasestorage.app',
  );

}